# Generated by Django 4.2.4 on 2023-09-11 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=25, verbose_name='contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('image', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('time', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='nombre')),
                ('lastname', models.CharField(max_length=25, verbose_name='apellido')),
                ('email', models.EmailField(max_length=30)),
                ('birthday', models.DateField()),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=25, verbose_name='direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel', models.CharField(max_length=25)),
                ('price', models.IntegerField()),
                ('departure', models.DateField()),
                ('arrival', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPython.users')),
            ],
        ),
    ]
